# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r_check_args: --as-cran
sudo: false
cache: packages
warnings_are_errors: false

matrix:
  include:
  - r: 3.4
  - r: 3.5
  - r: devel
  - r: oldrel
  - r: release
    before_cache:
      - Rscript -e 'remotes::install_cran("pkgdown")'
      - Rscript -e 'remotes::install_cran("covr")'
    after_success:
      - Rscript -e 'covr::codecov()'
      - R CMD INSTALL .
      - Rscript -e 'pkgdown::build_site()'
    deploy:
      - provider: pages
        skip-cleanup: true
        github-token: $GITHUB_PAT
        keep-history: true
        local-dir: docs
        on:
          branch: master
